import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DYPCET AI Chat",
  description: "Generated by create next app",
};

import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-grow container mx-auto px-4 py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}



export const testimonials = [
  {
    id: 1,
    name: "Rahul Sharma",
    course: "Computer Science Engineering",
    year: "2022 Batch",
    quote: "D.Y. Patil College has been transformative for my career. The faculty's guidance and cutting-edge curriculum have prepared me for real-world challenges.",
    image: "/student-images/rahul.jpg"
  },
  {
    id: 2,
    name: "Priya Patel",
    course: "Mechanical Engineering",
    year: "2021 Batch",
    quote: "The hands-on learning approach and state-of-the-art laboratories have been instrumental in my professional growth.",
    image: "/student-images/priya.jpg"
  },
  {
    id: 3,
    name: "Amit Deshmukh",
    course: "Electronics and Telecommunication",
    year: "2023 Batch",
    quote: "Incredible research opportunities and industry connections make this college stand out. I've already secured an internship with a top tech company!",
    image: "/student-images/amit.jpg"
  }
];
